# >, >=, <, <= ==, !=, is,in

print(3 > 2)
print(3 >= 2)
print(3 < 2)
print(3 <= 2)
print(3 == 3)
print(3 != 2)
print(3 == '3')
print(2 is 2)
print(2 is not 3)
print(2 is not 2)
print('F' in 'Finland')
print('land' in 'Finland')
print('Land' in 'Finland')